# Generated by Django 6.0.2 on 2026-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='zip',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
