# Generated by Django 6.0.2 on 2026-02-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
